### ISSUE TITLE
Unable to install after update

### ISSUE THREAD

**Issue by medianton** [jasonsanjose/brackets-sass#84]
After months of usage without any problem, I tried to update the extension via Brackets' extension manager, it failed, and now I'm unable to install the 1.0.4 version via manager nor manually.

Windows 8.1 user.

**Comment by jasonsanjose** [comment]
Thanks for reporting this @medianton. Have you restarted brackets yet? 

If not, could you try looking at the console log `Debug > Show Developer Tools` and paste that into a comment here?

**Comment by AntonVoltchok** [comment]
Same exact problem, I get error when adding the extension, and now I can't remove the extension either, it just says it will reload without removing. I tried both app manager inside brackets and from github, neither work, and I still can't remove it, just says error. I tried uninstalling and re-installing brackets, that didn't work either as I'm getting the exact same problem. I'm on windows 7, so it's apparently any windows version.  I would really hate to switch to another code editor since I love brackets, but I need to have major site changes up by Monday and this is holding everything up.

**Comment by AntonVoltchok** [comment]
Ok so here is a little update, I stopped using bourbon but never removed the path in brackets.json to bourbon, after I cleared the "includedPaths" it finally let me cleanly install the SASS plugin. So at least that solves 50% of the problem and I can stop panicking because at least I can compile. 

So the only problem I have now is that Live Preview crashes instantly the second I type anything into a .scss file. Like I said I can still compile so with saving/refreshing a bunch of times, at least I can get my project out by Monday. However I'm really hoping there is a fix for this because I really don't want to go back to Sublime haha. 

(also I disabled the sass plugin to see if live preview would crash with just CSS and it doesn't, works fine, so it's something with the plugin itself)

**Comment by AntonVoltchok** [comment]
Found a little hack around the problem:

medianton - first uninstall brackets, then reinstall it, if you still have the corrupted SASS plugin installed at this point it should let you cleanly remove it. Once removed, AGAIN uninstall and reinstall brackets. Then install the SASS plugin.

Now hit live preview, if you don't have have any issues, great, but if live preview crashes when sass tries to compile, here's the trick I got to make it work. Start live preview, don't type anything in brackets, but instead go to your chrome tab, right click it, and hit duplicate, now you're going to have a second tab. Go back to your initial live preview tab, and start typing, should work fine. I have no idea why the duplicate tab fixes crash on compiling, but somehow it does haha.

**Comment by jasonsanjose** [comment]
There are 2 potential workarounds for this uninstall problem:

1. Restart Brackets (make sure you don't have a .sass/.scss file open at startup), then uninstall via the Extension Manager (thanks @rgfx)
2. Quit Brackets, then manually delete the extension at `C:/Users/<your user name>/AppData/Roaming/Brackets/extensions/user/jasonsanjose.brackets-sass/`

I'll close this bug and use #81 to track the actual fix. I'll make sure to update the README too.
